-- AlterTable
ALTER TABLE `Status` MODIFY `leagueStatus` ENUM('UNREGISTERED', 'PENDING', 'APPROVED', 'DRAFT_ELIGIBLE', 'FREE_AGENT', 'RESTRICTED_FREE_AGENT', 'SIGNED', 'GENERAL_MANAGER', 'RETIRED', 'SUSPENDED') NOT NULL DEFAULT 'UNREGISTERED';
