-- AlterTable
ALTER TABLE `Accolades` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;

-- AlterTable
ALTER TABLE `Draft` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;

-- AlterTable
ALTER TABLE `Games` MODIFY `season` INTEGER NOT NULL DEFAULT 9,
    MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;

-- AlterTable
ALTER TABLE `Matches` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL,
    MODIFY `season` INTEGER NOT NULL DEFAULT 9;

-- AlterTable
ALTER TABLE `ModLogs` MODIFY `season` INTEGER NOT NULL DEFAULT 9;

-- AlterTable
ALTER TABLE `Records` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;

-- AlterTable
ALTER TABLE `Status` MODIFY `leagueStatus` ENUM('UNREGISTERED', 'PENDING', 'MANUAL_REVIEW', 'APPROVED', 'DRAFT_ELIGIBLE', 'FREE_AGENT', 'RESTRICTED_FREE_AGENT', 'SIGNED', 'GENERAL_MANAGER', 'RETIRED', 'SUSPENDED') NOT NULL DEFAULT 'UNREGISTERED';

-- AlterTable
ALTER TABLE `Substitute` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;

-- AlterTable
ALTER TABLE `Teams` MODIFY `tier` ENUM('RECRUIT', 'PROSPECT', 'APPRENTICE', 'EXPERT', 'MYTHIC', 'MIXED') NOT NULL;
